apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular15-app
spec:
  selector:
    matchLabels:
      app: angular15-app
  replicas: 1
  template:
    metadata:
      labels:
        app: angular15-app
    spec:
      containers:
        - name: angular15-app
          image: angular15-app:1.0.001
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: angular15-app-config
                  key: ENVIRONMENT
