kind: Service
apiVersion: v1
metadata:
  name: angular15-service
spec:
  selector:
    app: angular15-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
  type: NodePort
